app/main/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField, SelectField, BooleanField
from wtforms.validators import Required, Length
from ..models import User
from slackclient import SlackClient

class SessionForm(Form):
    session_name = StringField(
        'Session name', validators=[Required(), Length(1, 64)])
    language = SelectField(u'Programming Language', choices=[('py', 'Python')])
    submit = SubmitField('Create session')

class NameForm(Form):
    name = StringField('What is your name?', validators=[Required()])
    submit = SubmitField('Submit')

class ChatForm(Form):
    channel = SelectField(u'Channel', choices=[()])
    text = StringField('Enter Message here', validators=[Required()])
    submit = SubmitField('Send')
        

# TODO Implement in future @samson
class EditProfileAdminForm(Form):

    def __init__(self, user, *args, **kwargs):
        super(EditProfileAdminForm, self).__init__(*args, **kwargs)
        self.role.choices = [(role.id, role.name)
                             for role in Role.query.order_by(Role.name).all()]
        self.user = user

    def validate_email(self, field):
        if field.data != self.user.email and \
                User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered.')

    def validate_username(self, field):
        if field.data != self.user.username and \
                User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already in use.')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, redirect, url_for, request
from flask_login import current_user, login_required
from .forms import SessionForm
from . import main
from app import db
from ..models import User, CodeSession
from app.email import send_email
from firebase import firebase
from slackclient import SlackClient


session_url = ""
@main.route('/')
def index():
    session.permanent = True
    return render_template('main/home.html')

def list_channels():
    channels_call = slack_client.api_call("channels.list")
    if channels_call['ok']:
        return channels_call['channels']
    return None


def channel_info(channel_id):
    channel_info = slack_client.api_call("channels.info", channel=channel_id)
    if channel_info:
        return channel_info['channel']
    return None

# Send message
def send_message(channel_id, message):
    slack_client.api_call(
        "chat.postMessage",
        channel=channel_id,
        text=message,
        username=current_user.username,
        icon_emoji=':robot_face:'
    )

# Recieving messages
@main.route('/slack', methods=['POST'])
def inbound():
    if request.form.get('token') == SLACK_WEBHOOK_SECRET:
        channel = request.form.get('channel_name')
        username = request.form.get('user_name')
        text = request.form.get('text')
        inbound_message = username + " in " + channel + " says: " + text
        print(inbound_message)
    return Response(), 200


@main.route('/', methods=['GET'])
def test():
    return Response('It works!')


# Initiates a new session on user request
@main.route('/new', methods=['GET', 'POST'])
def new_session():
    form = SessionForm()
    if form.validate_on_submit():
        session_ = CodeSession(session_name=form.session_name.data, session_lang=form.language.data)
        if current_user.id is not None:
            user_ = User.query.get(current_user.id)
            user_.sessions.append(session_)
            db.session.add(user_)
            db.session.commit()
        return redirect(url_for('main.session'))
    return render_template('main/new_session.html', form=form)

# Sends out the request via an email for code pairing
# Queries for all the users currently registered for pairing
@main.route('/session', methods=['GET', 'POST'])
@login_required
def session():
    users = User.query.all()
    if request.method == 'POST':
        for user in users:
            if str(user.username+' ') == str(request.form.get('usernames')):
                print user.username
                session_link = request.form.get('session_link')
                send_email(current_user.email, user.email, "Pear Invite", 'mail/invite', user=user,  current_user=current_user,
                           session_link=session_link)
                print str(session_link)
    return render_template('main/session.html', users=users)

# Queries the firebase for all the existing session
# Checks for sessions created by current_user and renders the session in table
@main.route('/sessions')
@login_required
def my_session():
        fire = firebase.FirebaseApplication('https://pear-1dd83.firebaseio.com/')
        results = fire.get('https://pear-1dd83.firebaseio.com/', None)
        sess_hash = []
        for result in results:
            for x in results[result]:
               if str(current_user.username) == str(results[result][x].get('username')).strip():
                   sess_hash.append(str(results[result][x].get('session')))
        return render_template('main/my_sessions.html', sess_hash=sess_hash)

# Gets the session from firebase and loads its instance
# Uses the hashed key to track each session
@main.route('/edit/<hashed>')
def edit(hashed):
    global session_url
    #TODO followup
    session_url = "http://pearpro.herokuapp.com/session#"+hashed
    return redirect(session_url)

# Queries the firebase database for the session Id and deletes it from firebase
@main.route('/delete/<hashed>')
@login_required
def delete(hashed):
    fire = firebase.FirebaseApplication('https://pear-1dd83.firebaseio.com/')
    results = fire.get(current_user.username + '  ', None)
    for result in results:
        print results[result]
        if results[result].get('session') == hashed:
            fire.delete(current_user.username + '  ', result)
    return redirect(url_for('main.my_session'))


if __name__ == '__main__':
    channels = list_channels()
    if channels:
        print("Channels: ")
        for channel in channels:
            print(channel['name'] + " (" + channel['id'] + ")")
            detailed_info = channel_info(channel['id'])
            if detailed_info:
                print('Latest text from ' + channel['name'] + ":")
                print(detailed_info['latest']['text'])
            if channel['name'] == 'general':
                send_message(channel['id'], "Hello " +
                             channel['name'] + "! It worked!")
        print('-----')
    else:
        print("Unable to authenticate.")

app/templates/main/home.html
{% extends "base.html" %}

{% block head %}{{ super() }}
    <style>
    .navbar{
        margin-bottom: 0;
    }
    </style>
{% endblock %}

{% block content %}
    <body background="{{ url_for('static', filename='img/header-copy.jpg') }}" id="bg" alt=""/body>
    <div class="page-header col-md-12">
    	<h3>Welcome to Pair Programming</h3>
    </div>
    <div class="col-md-6">
    	<p>Get ready to have a productive session in <strong>3 Simple Steps</strong></p>
    	<h4><strong>
    		<ol type="1)">
  			<li>Create/Load Session</li><br>
  			<li>Invite Your Team</li><br>
  			<li>Chat🤓 & Code💻</li>
			</ol>
		</strong></h4>
    </div>
    <div class="col-md-4 col-md-offset-4">
            <div>

                <img src="{{ url_for('static', filename='img/test.png') }}">


            </div>
        

        
{% endblock %}

app/templates/main/my_sessions.html
{% extends "base.html" %}
{% block content %}


<div class="container">
<body background="{{ url_for('static', filename='img/header.jpg') }}" id="bg" alt=""/body>
  <h2>Current Sessions </h2>
  <table class="table table-bordered table-bg-warning">
    <thead class="thead-default">
      <tr>
        <th>Sessions</th>
      </tr>
    </thead>
    <tbody>
        {% for sess in sess_hash %}
            <tr>
                <td>{{ sess }}</td>
                <td><a href="{{ url_for('main.edit', hashed=sess) }}"><strong>EDIT</strong></a></td>
                <td><a href="{{ url_for('main.delete', hashed=sess) }}"><strong>DELETE</strong></a></td>
            </tr>
        {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/main/new_session.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Pear - New session{% endblock %}
{% block content %}
        <div class="col-md-8 col-md-offset-0">
        	<body background="{{ url_for('static', filename='img/header-copy.jpg') }}" id="bg" alt=""/body>
            <div class="page-header">

                <h1>Create new session</h1>

            </div>
            <div class="col-md-6">
            
                {{ wtf.quick_form(form) }}

            </div>

            <div class="col-md-6">

                
            </div>
        </div>
        <div class="col-md-1">
            <div>

                <img src="{{ url_for('static', filename='img/test.png') }}">


            </div>
        

        
        </div>
{% endblock %}

app/templates/main/session.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html"  as wtf %}

{% block title %} Pear - Session{% endblock %}

{% block content %}

<body background="{{ url_for('static', filename='img/header-copy.jpg') }}" id="bg" alt=""/body>
<p id="username" hidden>{{ current_user.username }}  </p>
<p id="session_id"  hidden>{{ current_user.id}}</p>
<div class="container">
    <div class="row">
        <div class="col-md-3 col-md-offset-0">
  <h2>Pair</h2>
        <form role="form" method="post" action="{{ url_for('main.session') }}">
            <div class="form-group">
            
                <label for="sel1">Select a user to pair code</label>
                    <select class="form-control" name="usernames">
                        {% for user in users %}
                            <option value="{{ user.username }} ">{{ user.username  }}  </option>
                        {% endfor %}
                    </select>
                      <div class="form-group">
                        <label for="session_link">Paste session Link:</label>
                        <input  class="form-control"  name="session_link" placeholder="Session link">
                      </div>
                </div>
                <input type="submit" class="btn btn-primary" value="Send Invite">
        </form>
        <br>
        <div class="page-header"></div>
  <h3>Broadcast Messages</h3>
        <form role="form" method="post" action="{{ url_for('main.session') }}">
            <div class="form-group">
                <label for="sel1">Select Slack Channel</label>
                    <select class="form-control" name="usernames">
                        {% for user in users %}
                            <option value="{{ user.username }} ">{{ Channel  }}  </option>
                        {% endfor %}
                    </select>
                      <div class="comment-form">
                        <label for="session_link">Message Content:</label>
                        <input  class="form-control"  name="session_link" placeholder="Message Content">
                      </div>
                </div>
                <input type="submit" class="btn btn-primary" value="Send">
        </form>
        </div>
        <div class="col-md-8">
           <div id="firepad"></div>
        </div>
            <div class="col-md-2">
            </div>
        </div>
    </div>
{% block scripts %} {{super()}}
<!-- firebase -->
<script src="https://cdn.firebase.com/js/client/2.3.2/firebase.js"></script>
<!-- ace  -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.2/ace.js"></script>
<!-- firepad -->

<script src="https://cdn.firebase.com/libs/firepad/1.3.0/firepad.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script src="{{ url_for('static', filename="js/editor.js") }}"></script>
<script src="{{ url_for('static', filename="js/editor.js") }}"></script>
{% endblock %} {% endblock %}